store:
  name: nedb
  path: ./db
port: 80
templates: './templates'
badges: 
  - 'eslint-errors'
  - 'eslint-warnings'
  - 'flow-coverage'
  - 'test-coverage'
  - 'vue-component-decorator'
  - 'code-size'
  - 'project-size'
  - 'js-size'
  - 'css-size'
  - 'tests-status'
  - 'commits'
  - 'components-count'
  - 'files-count'
  - 'lines-of-code'
  - 'version'
  - 'npm-version'
  - 'pull-requests'
  - 'todos'